---
- hosts: all
  become: true
  tasks:
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest
    - name: uploading default index.html for host
      copy:
        src: /home/ubuntu/ansible/index.html
        dest: /var/www/html
    - name: start httpd
      service:
        name: apache2

