---
- hosts: all
  become: true
  connection: ssh
  vars_prompt:
    - name: pkginstall
      prompt: Which package do you want to install?
      default: telnet
      private: no
  tasks:
    - name: Install the package {{ pkginstall }}
      apt: pkg={{ pkginstall }} state=latest
