---
- hosts: all
  become: true
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install {{ web_package }} package
      apt:
        name: "{{ web_package }}"
        state: latest
    - name: Install {{ db_package }} package
      apt:
        name: "{{ db_package }}"
        state: latest
    - name: Install {{ db_service }} package
      service:
        name: "{{ db_service }}"
        state: started

  vars:
    web_package: apache2
    db_package: mariadb-server
    db_service: mariadb
